[project]
name = "lektor-imgutils"
version = "0.1"
description = "Image handling utilities for Lektor."
readme = "README.rst"

authors = [{name = "H. Turgut Uyar", email = "uyar@tekir.org"}]
license = {file = "LICENSE.txt"}

keywords = ["lektor", "plugin", "image", "responsive", "srcset", "picture"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Plugins",
    "Framework :: Lektor",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Internet",
    "Topic :: Internet :: WWW/HTTP :: Site Management",
]

requires-python = "~=3.8"
dependencies = [
    "beautifulsoup4",
    "pillow",
    "pillow-avif-plugin",
    "jxlpy",
]

[project.optional-dependencies]
style = ["ruff"]
dev = [
    "lektor-imgutils[style]",
    "build",
]

[project.entry-points."lektor.plugins"]
imgutils = "lektor_imgutils:ImgUtilsPlugin"

[project.urls]
repository = "https://github.com/uyar/lektor-imgutils"

[tool.setuptools]
packages = ["lektor_imgutils"]

[tool.ruff]
select = ["E", "F", "I"]
ignore = ["E731"]
line-length = 79

[tool.ruff.isort]
lines-after-imports = 2

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
